### ISSUE TITLE
Github action: whelk-io/maven-settings-xml-action was archived and must be replaced

### ISSUE THREAD

**Issue by ariwk** [SchweizerischeBundesbahnen/open-source-polarion-java-repo-template#80]
The whelk-io/maven-settings-xml-action has been archived, which means it's no longer being maintained. 

Here are some alternatives for GitHub Actions for Maven settings.xml we can use instead:

1. **s4u/maven-settings-action**
   This is a popular alternative that provides similar functionality:
   ```yaml
   - name: Configure Maven Settings
     uses: s4u/maven-settings-action@v2.8.0
     with:
       servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}"}]'
       repositories: '[{"id": "central", "url": "https://repo1.maven.org/maven2"}]'
   ```

2. **Create settings.xml manually**
   You can create the settings.xml file directly in your workflow:
   ```yaml
   - name: Setup Maven settings.xml
     run: |
       mkdir -p ~/.m2
       echo "<settings>
         <servers>
           <server>
             <id>github</id>
             <username>${{ github.actor }}</username>
             <password>${{ secrets.GITHUB_TOKEN }}</password>
           </server>
         </servers>
       </settings>" > ~/.m2/settings.xml
   ```

3. **actions/setup-java with settings path**
   The official GitHub Java setup action supports Maven settings:
   ```yaml
   - name: Set up Java and Maven
     uses: actions/setup-java@v3
     with:
       java-version: '17'
       distribution: 'temurin'
       server-id: github
       server-username: GITHUB_ACTOR
       server-password: GITHUB_TOKEN
       settings-path: ${{ github.workspace }}
   ```

These alternatives provide the same core functionality of configuring Maven to work with private repositories or GitHub Packages during your CI/CD workflows. The s4u/maven-settings-action is particularly popular as a direct replacement for the archived whelk-io action.
